# Generated by Django 3.2.25 on 2024-04-09 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20240408_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='country',
            field=models.CharField(choices=[('Ireland', 'Ireland')], default='Ireland', editable=False, max_length=80),
        ),
        migrations.AlterField(
            model_name='order',
            name='county',
            field=models.CharField(max_length=80),
        ),
    ]
