# Generated by Django 3.2.25 on 2024-06-12 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faqs',
            options={'verbose_name_plural': 'FAQs'},
        ),
    ]
