# Generated by Django 3.2.25 on 2024-06-18 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_aboutus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faqs',
            options={'verbose_name': 'FAQs', 'verbose_name_plural': 'FAQs'},
        ),
    ]
